databases:
  - name: NBA_BET_KANSAS_ST
    databaseName: NBA_BET_KANSAS_ST
    user: NBA_BET_KANSAS_ST

services:
  - type: web
    name: NBA_BET_KANSAS_ST
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn NBA_BET_KANSAS_ST.wsgi:application"
    envVars:
      - key: POETRY_VERSION
        value: 1.5.1
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: DATABASE_URL
        fromDatabase:
          name: mysite
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4