# Generated by Django 3.2.6 on 2021-10-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank1',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 1'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank10',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 10'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank2',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 2'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank3',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 3'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank4',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 4'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank5',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 5'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank6',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 6'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank7',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 7'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank8',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 8'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='east_rank9',
            field=models.CharField(choices=[('Philadelphia 76ers', 'Philadelphia 76ers'), ('Brooklyn Nets', 'Brooklyn Nets'), ('Milwaukee Bucks', 'Milwaukee Bucks'), ('New York Knicks', 'New York Knicks'), ('Charlotte Hornets', 'Charlotte Hornets'), ('Atlanta Hawks', 'Atlanta Hawks'), ('Boston Celtics', 'Boston Celtics'), ('Miami Heat', 'Miami Heat'), ('Indiana Pacers', 'Indiana Pacers'), ('Chicago Bulls', 'Chicago Bulls'), ('Toronto Raptors', 'Toronto Raptors'), ('Washington Wizards', 'Washington Wizards'), ('Orlando Magic', 'Orlando Magic'), ('Cleveland Cavaliers', 'Cleveland Cavaliers'), ('Detroit Pistons', 'Detroit Pistons')], max_length=40, verbose_name='East Rank 9'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank1',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 1'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank10',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 10'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank2',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 2'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank3',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 3'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank4',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 4'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank5',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 5'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank6',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 6'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank7',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 7'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank8',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 8'),
        ),
        migrations.AlterField(
            model_name='nbabetter',
            name='west_rank9',
            field=models.CharField(choices=[('Utah Jazz', 'Utah Jazz'), ('Phoenix Suns', 'Phoenix Suns'), ('LA Clippers', 'LA Clippers'), ('Los Angeles Lakers', 'Los Angeles Lakers'), ('Denver Nuggets', 'Denver Nuggets'), ('Portland Trail Blazers', 'Portland Trail Blazers'), ('San Antonio Spurs', 'San Antonio Spurs'), ('Dallas Mavericks', 'Dallas Mavericks'), ('Memphis Grizzlies', 'Memphis Grizzlies'), ('Golden State Warriors', 'Golden State Warriors'), ('Sacramento Kings', 'Sacramento Kings'), ('New Orleans Pelicans', 'New Orleans Pelicans'), ('Oklahoma City Thunder', 'Oklahoma City Thunder'), ('Houston Rockets', 'Houston Rockets'), ('Minnesota Timberwolves', 'Minnesota Timberwolves')], max_length=40, verbose_name='West Rank 9'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='data',
            field=models.CharField(max_length=600),
        ),
    ]
