# Generated by Django 3.2.6 on 2021-10-23 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better', '0003_alter_teams_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teams',
            name='data',
            field=models.CharField(max_length=10000),
        ),
    ]
