# Generated by Django 3.2.6 on 2021-10-23 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Timer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.CharField(max_length=50)),
                ('daySinceLastUpdated', models.CharField(max_length=50)),
            ],
        ),
    ]
